complexity:
  LongParameterList:
    ignoreDefaultParameters: true

style:
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  UnusedPrivateMember:
    ignoreAnnotated: [ 'preview' ]
  WildcardImport:
    active: false
  UnusedParameter:
    active: false

naming:
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9_]*'
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]

empty-blocks:
  EmptyClassBlock:
    active: false
  EmptyKtFile:
    active: false