name: Android CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create Google Services
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > app/google-services.json

      - name: Access KAKAO_APP_KEY
        run: echo KAKAO_APP_KEY=\"$API_KEY\" >> local.properties
        shell: bash
        env:
          API_KEY: ${{ secrets.KAKAO_APP_KEY }}

      - name: Access FACEBOOK_CLIENT_ID
        run: echo FACEBOOK_CLIENT_ID=\"CLIENT_ID\" >> local.properties
        shell: bash
        env:
          CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID }}

      - name: Access FACEBOOK_CLIENT_TOKEN
        run: echo FACEBOOK_CLIENT_TOKEN=\"CLIENT_TOKEN\" >> local.properties
        shell: bash
        env:
          CLIENT_TOKEN: ${{ secrets.FACEBOOK_CLIENT_TOKEN }}

      - name: Access NAVER_API_MAP_KEY
        run: echo NAVER_API_MAP_KEY=\"API_KEY\" >> local.properties
        shell: bash
        env:
          API_KEY: ${{ secrets.NAVER_API_MAP_KEY }}

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Run detekt
        run: ./gradlew detekt

      - name: Android Test Report Action
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}

      - name: Build assemble Debug APK
        run: ./gradlew assembleDebug